### ISSUE TITLE
Character limit when sending a message

### ISSUE THREAD

**Issue by WORMSTweaker** [flifloo/SecureSocketService#2]
Sending a message with too much characters will generate an Invalid Token

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cryptography-2.7-py3.6-linux-x86_64.egg/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/usr/local/lib/python3.6/dist-packages/cryptography-2.7-py3.6-linux-x86_64.egg/cryptography/hazmat/primitives/hmac.py", line 66, in verify
    ctx.verify(signature)
  File "/usr/local/lib/python3.6/dist-packages/cryptography-2.7-py3.6-linux-x86_64.egg/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 54, in listen_client
    data = self.receive(self.clients[name])
  File "/usr/local/lib/python3.6/dist-packages/SecureSocketService-1.0.1-py3.6.egg/SecureSocketService/__init__.py", line 44, in receive
    response = self.fernet.decrypt(response)
  File "/usr/local/lib/python3.6/dist-packages/cryptography-2.7-py3.6-linux-x86_64.egg/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/usr/local/lib/python3.6/dist-packages/cryptography-2.7-py3.6-linux-x86_64.egg/cryptography/fernet.py", line 117, in _decrypt_data
    self._verify_signature(data)
  File "/usr/local/lib/python3.6/dist-packages/cryptography-2.7-py3.6-linux-x86_64.egg/cryptography/fernet.py", line 106, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken
```

**Comment by flifloo** [comment]
Fix on commit [42fc2f0](https://github.com/flifloo/SecureSocketService/commit/42fc2f09df485ca25aba0d157917e488bddd29c4)
